name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: randomPeers
      run: node randomPeers/starter.js

    - name: someSet
      run: node someSet/starter.js

    - name: syntaxeErreur
      run: node syntaxeErreur/starter.js

    - name: wordOfCode
      run: |
        cd wordOfCode
        npm install
        npm start